apiVersion: batch/v1
kind: Job
metadata:
 generateName: dreamer-
 labels:
   kueue.x-k8s.io/queue-name: eidf079ns-user-queue
spec:
 completions: 1
 parallelism: 1
 template:
  spec:
   restartPolicy: Never
   containers:
   - name: jax-con
     image: nvcr.io/nvidia/jax:24.04-py3
     volumeMounts:
      - mountPath: /dev/shm
        name: dshm
     command: [/bin/bash, -c, --]
     args: 
       - |
         export OMP_NUM_THREADS=1;
         mkdir build;
         cd build;
         apt update; apt upgrade -y; apt install git vim -y;
         git clone https://github.com/maxweissenbacher/dreamer_flows.git;
         cd dreamer_flows;
         git checkout test;
         pip install -r requirements_test.txt;
         wandb login ac8ec66b318e6624089b2723c3174f01a850416c;
         cd dreamer;
         # python -c "import jax; print('jax version', jax.__version__); from jax.lib import xla_bridge; print(xla_bridge.get_backend().platform)"
         python run_files/main_train_eval.py \
               --jax.platform gpu \
               --envs.amount 1 \
               --loss_scales.reward 10 \
               --imag_horizon 15 \
               --batch_size 64 \
               --run.train_ratio 64 \
               --logdir_dirname Experiments/ \
               --logdir_expname ks_num_envs_1 \
               --wandb.project dreamer_ks_compare_n_envs_2;
     resources:
      requests:
       cpu: 8
       memory: "64Gi"
      limits:
       cpu: 8
       memory: "64Gi"
       nvidia.com/gpu: 1
   nodeSelector:
    nvidia.com/gpu.product: NVIDIA-A100-SXM4-40GB
   volumes:
   - name: dshm
     emptyDir:
      medium: Memory
